version: "3.8"

services:
  nginx:
    build:
      context: ./nginx/ # Corrected context path
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - php
  php:
    build:
      context: ./php/
    container_name: php
  mysql:
    build:
      context: ./mysql/
    container_name: mysql
    environment:
      # MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: euphoria
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./euphoria1.sql:/docker-entrypoint-initdb.d/euphoria1.sql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
